### ISSUE TITLE
call onLanguageChange() on startup?

### ISSUE THREAD

**Issue by Obiwarn** [yoolab/i18n-conf#10]
Why is it not called on startup (or when I reload a page)?

If I manually set language on startup, then language change is called twice sometimes (by me and by your package).

**Comment by martinopic** [comment]
Language change listeners (I think you are referring to that) are called whenever `I18NConf.setLanguage` is called. 

There are just a couple of cases when these are not called:

1) In case the method is called with a non supported language
2) In case the method is called with a language which is the same of the current language (that's not a "language change")

An console warning is outputted for each of these cases.

The package just use `I18NConf.setLanguage` if `autoConfLanguage` is set to true, otherwise is up to the developer to set the language.

**Comment by Obiwarn** [comment]
e.g. 
when I run your example code 

and reload http://localhost:3000/it

the "current language is: it"

but the displayed is en

so I guess one has to set the lang in startup, right?

**Comment by martinopic** [comment]
Good point :-) You're helping a lot @obiwarn, thanks. Not sure whether this is a i18n-conf problem or an iron-router-i18n problem, I'll look into it.

**Comment by martinopic** [comment]
I made a modification on Iron Router i18n to solve this (see https://github.com/yoolab/iron-router-i18n/issues/74) but I want to reflect some more if there might a cleaner solution by modifying i18n-conf behavior so even if the specific issue is solved just by using Iron Router i18n 1.2.2 (is it?) I'll leave the ticket open.

**Comment by Obiwarn** [comment]
I couldn't find an update to i18n conf on atmosphere to test it.

**Comment by Obiwarn** [comment]
Old bug is OK now.

New bug. "Reload" page with a link on the page:

open localhost/en
click a link there that redirects to  localhost/en 
error:
Warning: asked to change language to [de] but this is already the current language.

**Comment by martinopic** [comment]
This is related to https://github.com/yoolab/iron-router-i18n/issues/75 and the root cause for this problem

**Comment by aldo-n** [comment]
i18nconf.js:97
You actually still have the warning line in this package and this still prints out the warning
